language: elixir
elixir:
  - 1.8.1
  - 1.9.1
otp_release:
  - 20.0
  - 21.0
  - 22.0

cache:
  directories:
  - deps
  - _build

env:
  global:
    - MIX_ENV=test

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  # Check that code is formatted
  - "mix format --dry-run --check-formatted"
  # Run all tests except pending ones
  - "mix test --trace"

jobs:
  include:
    - stage: code_coverage
      script:
        - "mix deps.get"
        # Push code coverage
        - "mix coveralls.travis"
      elixir: 1.9.1
      otp_release: 22.0
